# ci-overlays/openjdk-riscv/kustomization.yaml
namespace: github-runners

resources:
- ../../base

nameSuffix: -openjdk

patches:
- target:
    kind: Deployment
    name: github-runner
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "https://github.com/alitariq4589/openjdk-riscv"
    - op: replace
      path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/key
      value: "openjdk-riscv-token"
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: "pioneer-1-kubernetes-openjdk"