apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - network-policy.yaml
  - resource-quota.yaml
  - runner.yaml

commonLabels:
  managed-by: kustomize
  component: ci-runner