apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-runners

resources:
  - ../../base

nameSuffix: -nodejs

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "https://github.com/alitariq4589/nodejs-riscv"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/key
        value: "nodejs-riscv-token"
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "pioneer-1-kubernetes-nodejs"
    target:
      kind: Deployment
      name: github-runner